#!/bin/sh

$LAMBDA_TASK_ROOT/jre19-slim/bin/java \
    --add-opens java.base/java.util=ALL-UNNAMED \
    -XX:+TieredCompilation \
    -XX:TieredStopAtLevel=1 \
    -XX:+UseSerialGC \
    -jar json-path-api-all.jar "$_HANDLER"
