= Json Path API

A Web API that wraps https://github.com/json-path/JsonPath library calls.

*tl;dr*

Client/Browser -> Amazon Route53 -> Amazon API Gateway -> AWS Lambda -> Jayway JsonPath Library

== Build and Deploy Commands

To build and deploy into your own AWS account, follow this:

[source]
----
# Build the zip file that contains the artifacts necessary for the Lambda (you need Docker for this to run successfully)
./gradlew clean buildZip

# Set S3 bucket and object where the zip will be uploaded
export STACK_NAME=json-path-api-custom-j19
# Use a bucket from your AWS account
export S3_BUCKET=sumiya
export S3_KEY=lambdas/json-path

# Upload the built zip to S3
aws s3 cp build/distributions/json-path-api-1.0-SNAPSHOT.zip s3://$S3_BUCKET/$S3_KEY/JsonPathEvaluator.zip

# Create stack (one-time step) - this creates the Lambda function and the API Gateway endpoint (note it down)
sam deploy --s3-bucket $S3_BUCKET --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --template-file cloudformation/template.yaml

# (Optional) Update function after re-uploading a newly built zip
aws lambda update-function-code --function-name JsonPathEvaluator --s3-bucket $S3_BUCKET --s3-key $S3_KEY/JsonPathEvaluator.zip

# (Optional) Delete stack when you are done and do not need to retain the resources.
aws cloudformation delete-stack --stack-name $STACK_NAME
----

== Test the API Endpoint

Replace the endpoint with the newly generated api in the below command and test.
----
curl -X POST https://83dypaxnz0.execute-api.us-west-2.amazonaws.com/dev/jsonpath -H "Content-Type: application/json" -d \
'{
  "jsonToEvaluate" : "[{\"foo\" : \"foo1\",\"bar\" : \"bar1\"}{\"foo\" : \"foo2\"}]",
  "pathExpression" : "$[*].bar",
  "jsonPathOptions" : ["SUPPRESS_EXCEPTIONS","ALWAYS_RETURN_LIST"]
}'
----

== Customizing the API Endpoint

Beyond the template used in this repo, it is possible to further customize the API.

For example, a custom API domain was manually setup with the right certificate, and corresponding Route 53 records were created to route requests to this custom domain.

That customized API is currently deployed here: `https://jsonpath.sumiya.page/jsonpath`. An API Key is needed to invoke this endpoint.

Sample curl:

----
curl -X POST https://jsonpath.sumiya.page/jsonpath -H 'X-API-Key: <insert-api-key-here>' -H "Content-Type: application/json" -d \
'{
  "jsonToEvaluate" : "[{\"foo\" : \"foo1\",\"bar\" : \"bar1\"}{\"foo\" : \"foo2\"}]",
  "pathExpression" : "$[*].bar",
  "jsonPathOptions" : ["SUPPRESS_EXCEPTIONS","ALWAYS_RETURN_LIST"]
}'
----

If you intend to use a front-end, you may find this useful: https://github.com/psumiya/til/blob/main/http/options/cors.adoc

Here is a web application that uses a customized API endpoint as described above: https://sumiya.page/jpath.html

== Runtime Evolution
- Current Runtime: Java 21
- Architecture: ARM64

In the past, I wrote about how the JRE for this project evolved from Java 11 to a custom Java 19 runtime here: https://sumiya.page/aws-lambda-custom-runtime-with-java-and-gradle.html